### ISSUE TITLE
Map ChainID/Address to Bundlr currency string

### ISSUE THREAD

**Issue by MantisClone** [MantisClone/arweave-upload#10]
```json
{ 
  "chainId_tokenAddress" : "bundlrString"
}
```

- [x] For native tokens, use 0x000... token address
- [ ] Token addresses should be checksummed

**Comment by corrie-sloot** [comment]
ethereum, chain 1, tokenAddress = 0x0
matic, chain 137, tokenAddress = 0x0
bnb, chain 56, tokanAddress = 0x0
arbitrum, chain 42161, tokanAddress = 0x0
avalanche, chain 43114, tokenAddress = 0x0
boba, chain 288, tokenAddress = 0xa18bF3994C0Cc6E3b63ac420308E5383f53120D7
boba-eth, chain 288, tokenAddress = 0x0
