### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by MantisClone** [MantisClone/arweave-upload#17]
@corrie-sloot

Questions:

1. Why do we use `cors` middleware? https://expressjs.com/en/resources/middleware/cors.html
2. Why do we use `bodyParser.urlencoded`? All of the endpoints take only JSON input.
3. Why do we disallow good crawlers in robots.txt?

**Comment by corrie-sloot** [comment]
1. Don't need cors, since no browser should be talking to us. Removed.
2. When I take out bodyParser.urlencoded, it fails. I don't remember why I put this in.
3. We don't want any search engines indexing our API. Would just consume resources and provide no use.
