### ISSUE TITLE
Add more Quote status codes to indicate failure modes

### ISSUE THREAD

**Issue by MantisClone** [MantisClone/arweave-upload#21]
When a quote is being processed, there are many different ways that it could fail.  Some of these failures (like missing or insufficient approval) are non-recoverable failures.  Other failures (like rate-limited node providers, arweave server dies, IPFS gateway down) are recoverable failures that can be resolved with retries.

When non-recoverable failures occur, refund the user's funds.
When recoverable failures occur, retry some number of times, and eventually convert to non-recoverable failure and refund user's funds.

If the Arweave Upload server dies midway through processing a quote, it needs to restart the quote upon server startup.

To do this, we need to store error status codes in the database.

Possible solution:
- 201-299 = Processing payment failure modes
- 401-499 = Upload failure modes

On server startup, look through the database and restart any quotes with status 201-299 or 401-499.

**Comment by MantisClone** [comment]
@alexcos20 updated the DBS spec (and by extension the Arweave Upload Spec) to include more status codes.

Status | Status Description
-- | --
0 | No such quote
1-99 | Waiting for files to be uploaded by the user
100-199 | Processing payment
200-299 | Processing payment failure modes
300-399 | Uploading files to storage
400 | Upload done
401-499 | Upload failure modes

Reference: https://github.com/oceanprotocol/decentralized_storage_backend/issues/1#issue-1288532466

**Comment by balessan** [comment]
@MantisClone be careful that if you modify the specification too much it could make our (the Startin'blox) budget out-of-date.

The overall idea is good and needs to be considered though. Thanks for the input on the status code and different scenario.

**Comment by MantisClone** [comment]
@balessan Agreed, we are cautious about changing the spec. But this was a necessary change - otherwise, if our server died half way through processing a payment, it would be impossible for us to know where to resume it.
